import java.io._

import scala.collection.JavaConverters._
object Bla {
  def main(args: Array[String]): Unit = {
    Documentation.generatePages()
  }

  class DocPage(fileName: String,
                 text: String
                ) {
    def generateTextFile(): Unit = {
      val printWriter = new PrintWriter(new File(fileName))
      printWriter.write(text)
      printWriter.close()
      }
    }

  object Documentation {

    val readme: DocPage = {
      new DocPage("docs/index.md",
        """This is a very long string.
          |It contains newlines.
          |It is Markdown.
          |
          |# YES MARKDOWN
          |
          |Who would have thought that?
          |It also contains
          |```
          |arbitrary code
          |```
          |And some more `stuff` like that. Such as:
          |* This
          |* Stuff
          |* ReST is better
          |
          |Paragraph1
          |
          |Paragraph2.
        """.stripMargin
      )
    }
    val manual: DocPage = {
      new DocPage("docs/manual.md",
        """# Manual
        |
        |Some information
        |
        |# Usage
        |
        |Should be autogenerated
        |
        |# Example
        |Should be autogenerated.
        |""".stripMargin
      )
      }
    val docPages: List[DocPage]= List(readme, manual)
    def generatePages(): Unit = {
      for (docPage <- docPages){
        docPage.generateTextFile()
      }
    }
  }
}
